# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/GABoardGameGeek.xcworkspace
xcode_scheme: GABoardGameGeek-Example
xcode_sdk: iphonesimulator10.2


#before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example --repo-update

#script:
#  - set -o pipefail
#  - xcodebuild -version
#  - xcodebuild -showsdks
#  - xcodebuild test -workspace Example/GABoardGameGeek.xcworkspace -scheme GABoardGameGeek-Example -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' ONLY_ACTIVE_ARCH=YES | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'GABoardGameGeek'
