language: objective-c
osx_image: xcode7.2

xcode_project: GABoardGameGeek.xcodeproj
xcode_scheme: GABoardGameGeek
xcode_sdk: iphonesimulator9.2

after_success:
  - bash <(curl -s https://codecov.io/bash)